### ISSUE TITLE
Definir Passo-a-Passo interno da Milestone

### ISSUE THREAD

**Issue by FShinoda** [capybara-fepe/email-6x1#15]

**Comment by FShinoda** [comment]
- [ ] Definir secções
- [ ] Mural de Referencias
- [ ] Conceito
- [ ] Paleta
  - [ ] Creme/Of-white
  - [ ] Cor de enfase
  - [ ] Tons de cinza
  - [ ] Cores Farol
- [ ] Fonte
  - [ ] Decorativa
  - [ ] Comum pra texto
- [ ] Prototipação Mobile
  - [ ] secção 1
  - [ ] secção 2
  - [ ] secção N
- [ ] Prototipação Desktop
  - [ ] secção 1
  - [ ] secção 2
  - [ ] secção N
- [ ] Wireframe Mobile
- [ ] Wireframe Desktop
